package org.example; // Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class MainTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    private JavascriptExecutor js;
    private WebDriverWait wait;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        driver.manage().window().setSize(new Dimension(1536, 816));
    }

    @After
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
    private void slowDown() {
        try {
            Thread.sleep(300); // chỉnh tùy ý
        } catch (InterruptedException ignored) {}
    }
    // ====== HELPER METHODS ======

    // Chờ loader form của OrangeHRM biến mất
    private void waitForFormLoaderToDisappear() {
        wait.until(ExpectedConditions.invisibilityOfElementLocated(
                By.cssSelector(".oxd-form-loader")
        ));
    }

    private void safeClick(By locator) {
        waitForFormLoaderToDisappear();
        WebElement el = wait.until(ExpectedConditions.elementToBeClickable(locator));
        el.click();
        slowDown();
    }

    private void safeType(By locator, String text) {
        waitForFormLoaderToDisappear();
        WebElement el = wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
        el.clear();
        el.sendKeys(text);
    }

    private void selectEmployeeFromAutocomplete(String employeeName) {
        System.out.println(">>> BẮT ĐẦU selectEmployeeFromAutocomplete at " + java.time.LocalTime.now());

        WebElement input = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector(".oxd-autocomplete-text-input > input")
                )
        );
        input.clear();
        input.sendKeys(employeeName);

        try {
            Thread.sleep(1500);
        } catch (InterruptedException ignored) {}

        WebDriverWait autoWait = new WebDriverWait(driver, Duration.ofSeconds(30));

        System.out.println("    Đợi dropdown xuất hiện at " + java.time.LocalTime.now());

        WebElement option = autoWait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector(".oxd-autocomplete-dropdown .oxd-autocomplete-option")
        ));

        System.out.println("    TÌM THẤY option at " + java.time.LocalTime.now());

        option.click();

        System.out.println(">>> KẾT THÚC selectEmployeeFromAutocomplete at " + java.time.LocalTime.now());
    }

    @Test
    public void main() {
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

        // ===== LOGIN =====
        WebElement usernameInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.name("username"))
        );
        usernameInput.sendKeys("Admin");

        WebElement passwordInput = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.name("password"))
        );
        passwordInput.sendKeys("admin123");

        safeClick(By.cssSelector("button[type='submit']"));

        // ===== VÀO PIM, TẠO EMPLOYEE =====
        safeClick(By.linkText("PIM"));

        safeClick(By.cssSelector(".oxd-button--secondary:nth-child(1)")); // Add Employee

        safeType(By.name("firstName"), "John");
        safeType(By.name("lastName"), "Smith");

        safeClick(By.cssSelector(".oxd-button--secondary.orangehrm-left-space")); // Save employee

        // ===== VÀO ADMIN, TẠO USER 1: jsmith_new =====
        safeClick(By.linkText("Admin"));

        safeClick(By.cssSelector(".oxd-button--secondary:nth-child(1)")); // Add User

        // AUTOCOMPLETE 1
        selectEmployeeFromAutocomplete("John  Smith");

        safeClick(By.xpath("//label[contains(., 'User Role')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[contains(@class, 'oxd-select-option')]//span[normalize-space()='Admin']"));
        safeClick(By.xpath("//label[contains(., 'Status')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[@role='option']//span[normalize-space()='Enabled']"));

        safeType(By.xpath("//label[contains(., 'Username')]/../following-sibling::div//input"), "jsmith_new");
        safeType(By.xpath("//label[contains(., 'Password')]/../following-sibling::div//input"), "P@ssword123");
        safeType(By.xpath("//label[contains(., 'Confirm Password')]/../following-sibling::div//input"), "P@ssword123");

        safeClick(By.cssSelector(".oxd-button--secondary.orangehrm-left-space")); // Save

        // ===== LẠI VÀO FORM (theo script gốc) =====
        safeClick(By.cssSelector(".oxd-button--secondary:nth-child(1)")); // Add
        safeClick(By.cssSelector(".oxd-button--secondary.orangehrm-left-space")); // Save trống

        // ===== TẠO USER 2: jsmith_new1 (pass != confirm) =====
        safeClick(By.linkText("Admin"));
        safeClick(By.cssSelector(".oxd-button--secondary:nth-child(1)"));

        // AUTOCOMPLETE 2
        selectEmployeeFromAutocomplete("John  Smith");

        safeClick(By.xpath("//label[contains(., 'User Role')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[contains(@class, 'oxd-select-option')]//span[normalize-space()='Admin']"));
        safeClick(By.xpath("//label[contains(., 'Status')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[@role='option']//span[normalize-space()='Enabled']"));

        safeType(By.xpath("//label[contains(., 'Username')]/../following-sibling::div//input"), "jsmith_new1");
        safeType(By.xpath("//label[contains(., 'Password')]/../following-sibling::div//input"), "P@ssword123");
        safeType(By.xpath("//label[contains(., 'Confirm Password')]/../following-sibling::div//input"), "P@ssword456");

        safeClick(By.cssSelector(".oxd-button--secondary.orangehrm-left-space"));

        // ===== TẠO USER 3: jsmith_new (trùng username) =====
        safeClick(By.linkText("Admin"));
        safeClick(By.cssSelector(".oxd-button--secondary:nth-child(1)"));

        // AUTOCOMPLETE 3
        selectEmployeeFromAutocomplete("John  Smith");

        safeClick(By.xpath("//label[contains(., 'User Role')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[contains(@class, 'oxd-select-option')]//span[normalize-space()='Admin']"));
        safeClick(By.xpath("//label[contains(., 'Status')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[@role='option']//span[normalize-space()='Enabled']"));

        safeType(By.xpath("//label[contains(., 'Username')]/../following-sibling::div//input"), "jsmith_new");
        safeType(By.xpath("//label[contains(., 'Password')]/../following-sibling::div//input"), "P@ssword123");
        safeType(By.xpath("//label[contains(., 'Confirm Password')]/../following-sibling::div//input"), "P@ssword123");

        safeClick(By.cssSelector(".oxd-button--secondary.orangehrm-left-space"));

        // ===== TẠO USER 4: jsmith_new1 với pass ngắn "123" =====
        safeClick(By.linkText("Admin"));
        safeClick(By.cssSelector(".oxd-button--secondary:nth-child(1)"));

        // AUTOCOMPLETE 4
        selectEmployeeFromAutocomplete("John  Smith");

        safeClick(By.xpath("//label[contains(., 'User Role')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[contains(@class, 'oxd-select-option')]//span[normalize-space()='Admin']"));
        safeClick(By.xpath("//label[contains(., 'Status')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[@role='option']//span[normalize-space()='Enabled']"));

        safeType(By.xpath("//label[contains(., 'Username')]/../following-sibling::div//input"), "jsmith_new1");
        safeType(By.xpath("//label[contains(., 'Password')]/../following-sibling::div//input"), "123");
        safeType(By.xpath("//label[contains(., 'Confirm Password')]/../following-sibling::div//input"), "123");

        safeClick(By.cssSelector(".oxd-button--secondary.orangehrm-left-space"));

        // ===== CÁC BƯỚC SEARCH / FILTER (như trước) =====
        safeClick(By.linkText("Admin"));
        safeType(By.xpath("//label[contains(., 'Username')]/../following-sibling::div//input"), "jsmith_new");
        safeClick(By.cssSelector(".orangehrm-left-space"));

        safeClick(By.linkText("Admin"));
        safeClick(By.xpath("//label[contains(., 'User Role')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[contains(@class, 'oxd-select-option')]//span[normalize-space()='ESS']"));
        safeClick(By.cssSelector(".orangehrm-left-space"));

        safeClick(By.linkText("Admin"));
        safeType(By.xpath("//label[contains(., 'Username')]/../following-sibling::div//input"), "user_khong_ton_tai");
        safeClick(By.cssSelector(".orangehrm-left-space"));

        safeClick(By.linkText("Admin"));
        safeType(By.xpath("//label[contains(., 'Username')]/../following-sibling::div//input"), "abc");
        safeClick(By.xpath("//label[contains(., 'User Role')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[contains(@class, 'oxd-select-option')]//span[normalize-space()='ESS']"));
        safeClick(By.xpath("//label[contains(., 'Status')]/../following-sibling::div//div[contains(@class, 'oxd-select-text')]"));
        safeClick(By.xpath("//div[contains(@class, 'oxd-select-option')]//span[normalize-space()='Enabled']"));
        safeClick(By.cssSelector(".oxd-button--ghost"));

        // ===== LOGOUT =====
        safeClick(By.cssSelector(".oxd-userdropdown-tab"));
        safeClick(By.linkText("Logout"));

        driver.close();
    }
}