describe("cypress_e2e_orangehrm_login_add_emp_search", () => {
  it("cypress_e2e_orangehrm_login_add_emp_search", () => {
    cy.viewport(1179, 643);
    cy.visit("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    cy.get("form > div:nth-of-type(1) input").click();
    cy.get("form > div:nth-of-type(1) input").type("Admin");
    cy.get("form > div:nth-of-type(2) input").click();
    cy.get("form > div:nth-of-type(2) input").type("admin123");
    cy.get("button").click();
    cy.location("href").should("eq", "https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index");
    cy.get("li:nth-of-type(2) > a").click();
    cy.location("href").should("eq", "https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList");
    cy.get("div.orangehrm-header-container i").click();
    cy.location("href").should("eq", "https://opensource-demo.orangehrmlive.com/web/index.php/pim/addEmployee");
    cy.get("div.--name-grouped-field > div:nth-of-type(1) input").click();
    cy.get("div.--name-grouped-field > div:nth-of-type(1) input").type("John");
    cy.get("div:nth-of-type(3) input").click();
    cy.get("div:nth-of-type(3) input").type("Smith");
    cy.get("button.oxd-button--secondary").click();
    cy.wait(1000);
    cy.get("li:nth-of-type(1) > a").click();
    cy.location("href").should("eq", "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers");
    cy.get("div.orangehrm-header-container > button").click();
    cy.location("href").should("eq", "https://opensource-demo.orangehrmlive.com/web/index.php/admin/saveSystemUser");
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(1) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("form > div:nth-of-type(1) div:nth-of-type(2) > div > div:nth-of-type(2) > div > div").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").type("John Smith");
    cy.get('.oxd-autocomplete-option').contains('John Smith').click();
    cy.get("div:nth-of-type(3) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.get("div:nth-of-type(4) input").click();
    cy.get("div:nth-of-type(4) input").type("jsmith_new");
    cy.get("div.user-password-cell input").click();
    cy.get("div.user-password-cell input").type("P@ssword123");
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").click();
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").type("P@ssword123");
    cy.get("button.oxd-button--secondary").click();
    cy.wait(1000);
    cy.reload();
    cy.get("button.oxd-button--secondary").click();
    cy.reload();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(1) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("div:nth-of-type(3) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").type("John Smith");
    cy.get('.oxd-autocomplete-option').contains('John Smith').click();
    cy.get("div:nth-of-type(4) input").click();
    cy.get("div:nth-of-type(4) input").type("jsmith_new1");
    cy.get("div.user-password-cell input").click();
    cy.get("div.user-password-cell input").type("P@ssword123");
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").click();
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").type("P@ssword456");
    cy.get("button.oxd-button--secondary").click();
    cy.reload();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(1) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").type("John Smith");
    cy.get('.oxd-autocomplete-option').contains('John Smith').click();
    cy.get("div:nth-of-type(3) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.get("div:nth-of-type(4) input").click();
    cy.get("div:nth-of-type(4) input").type("jsmith_new");
    cy.get("div.user-password-cell input").click();
    cy.get("div.user-password-cell input").type("P@ssword123");
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").click();
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").type("P@ssword123");
    cy.get("button.oxd-button--secondary").click();
    cy.reload();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(1) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").type("John Smith");
    cy.get('.oxd-autocomplete-option').contains('John Smith').click();
    cy.get("div:nth-of-type(3) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.get("div:nth-of-type(4) input").click();
    cy.get("div:nth-of-type(4) input").type("jsmith_new1");
    cy.get("div.user-password-cell input").click();
    cy.get("div.user-password-cell input").type("123");
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").click();
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").type("123");
    cy.get("button.oxd-button--secondary").click();
    cy.reload();

    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(1) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").type("John Smith");
    cy.get('.oxd-autocomplete-option').contains('John Smith').click();
    cy.get("div:nth-of-type(3) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.intercept('GET', '/web/index.php/api/v2/admin/validation/user-name*').as('validateUserName');

    cy.get("div:nth-of-type(4) input").clear().type("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb");

    cy.wait('@validateUserName').then((interception) => {
      // In thử ra console để chắc chắn structure
      cy.log(JSON.stringify(interception.response.body));

      const body = interception.response.body;
      expect(body.error.status).to.eq('422');
      expect(body.error.data.invalidParamKeys).to.include('userName');
    });
    cy.get("div.user-password-cell input").click();
    cy.get("div.user-password-cell input").type("P@ssword123");
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").click();
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").type("P@ssword123");
    cy.get("button.oxd-button--secondary").click();

    cy.reload();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(1) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) label").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").click();
    cy.get("form > div:nth-of-type(1) > div > div:nth-of-type(2) input").type("John Smith");
    cy.get('.oxd-autocomplete-option').contains('John Smith').click();

    cy.get("div:nth-of-type(3) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.get("div:nth-of-type(4) input").click();
    cy.get("div:nth-of-type(4) input").type("<b>Username</b>");
    cy.get("div.user-password-cell input").click();
    cy.get("div.user-password-cell input").type("P@ssword123");
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").click();
    cy.get("div.user-password-row > div > div:nth-of-type(2) input").type("P@ssword123");
    cy.get("button.oxd-button--secondary").click();
    cy.reload();
    cy.get("li:nth-of-type(1) > a").click();
    cy.location("href").should("eq", "https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers");
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").type("jsmith_new");
    cy.get("div.oxd-table-filter button.oxd-button--secondary").click();
    cy.get("button.oxd-button--ghost").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(2) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("div.oxd-table-filter button.oxd-button--secondary").click();
    cy.get("button.oxd-button--ghost").click();
    cy.get("div.oxd-table-filter div:nth-of-type(3) input").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").type("user_khong_ton_tai");
    cy.get("div.oxd-table-filter button.oxd-button--secondary").click();
    cy.get("button.oxd-button--ghost").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").type("john");
    cy.get("div.oxd-form-row > div > div:nth-of-type(2) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Admin').click();
    cy.get("div:nth-of-type(4) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.get("button.oxd-button--ghost").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").type("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    cy.get("div.oxd-table-filter button.oxd-button--secondary").click();
    cy.get("button.oxd-button--ghost").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").type("<script>alert('XSS')</script>");
    cy.get("div.oxd-table-filter button.oxd-button--secondary").click();
    cy.get("button.oxd-button--ghost").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").click();
    cy.get("div.oxd-form-row > div > div:nth-of-type(1) input").type("jsmith_new");
    cy.get("div.oxd-form-row > div > div:nth-of-type(2) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('ESS').click();
    cy.get("div:nth-of-type(4) div.oxd-select-text-input").click();
    cy.get('.oxd-select-option').contains('Enabled').click();
    cy.get("button.oxd-button--ghost").click();
  });
});
